---
# Main ansible playbook
- name: Configure mirrors infrastructure
  hosts: servers
  become: true
  
  roles:
    - role: security
      tags: [security]
    - role: network
      tags: [network]
    - role: nginx
      tags: [nginx]
    - role: mirrors
      tags: [mirrors]
    - role: observability
      tags: [observability]
    # - role: maintenance
    #   tags: [maintenance]
    #   tags: [mirrors]
    # - role: prometheus
    #   tags: [prometheus]
    # - role: router
    #   tags: [router]
    # - role: tor
    #   tags: [tor]

  post_tasks:
    - name: Display mirrors configuration status
      ansible.builtin.debug:
        msg: "Mirrors infrastructure has been successfully configured"

- name: Configure router infrastructure
  hosts: routers
  become: true

  roles:
    - role: security
      tags: [security]
    - role: router
      tags: [router]

  post_tasks:
    - name: Display router configuration status
      ansible.builtin.debug:
        msg: "Router infrastructure has been successfully configured"

